x-arcane:
  # https://cdn.jsdelivr.net/gh/selfhst/icons@main/webp/
  icon: ${SELFHST_WEBP:-missing-icon-source}/it-tools.webp
  urls:
    - it-tools.vm1.REDACTED_DOMAIN_1

services:
  it-tools:
    image: corentinth/it-tools
    restart: unless-stopped
    container_name: ${STACK}
    networks:
      - proxy
    labels:
      - com.getarcaneapp.arcane.icon=${SELFHST_WEBP:-missing-icon-source}/${STACK:-arcane}.webp
      - "traefik.enable=true"
      - "traefik.http.routers.${STACK}.entrypoints=https"
      - "traefik.http.routers.${STACK}.rule=Host(`${STACK}.vm1.REDACTED_DOMAIN_1`)"
      - "traefik.http.routers.${STACK}.tls=true"
      - "traefik.http.routers.${STACK}.tls.certresolver=cloudflare"
      - "traefik.http.services.${STACK}.loadbalancer.server.port=80"
networks:
  proxy:
    external: true