name: &stack bentopdf

x-arcane:
  icon: *stack
  urls:
    - ${COMPOSE_PROJECT_NAME}.${DOMAIN}

networks:
  proxy:
    external: true

services:
  bentopdf:
    image: ghcr.io/alam00000/bentopdf:v2.8.8@sha256:6ef493c8e3bdbaa26c9bfcec330377ae95116fa00660ca0342769063197b1952
    volumes:
      - /etc/localtime:/etc/localtime:ro
    container_name: ${COMPOSE_PROJECT_NAME}
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=https
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_PROJECT_NAME}.${DOMAIN}`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=cloudflare
      - traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=8080