name: &stack arcane

x-arcane:
  icon: *stack
  urls:
    - ${COMPOSE_PROJECT_NAME}.${DOMAIN}

networks:
  proxy:
    external: true

volumes:
  appdata:

services:
  arcane:
    container_name: *stack
    image: ghcr.io/getarcaneapp/arcane:latest
    env_file:
      - .env.secrets
    restart: unless-stopped
    ports:
      - 3552:3552
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /app/data/projects:/app/data/projects
      - appdata:/app/data
    user: 1000:1000
    environment:
      APP_URL: https://${COMPOSE_PROJECT_NAME}.${DOMAIN}
      TRUSTED_PROXIES: 172.16.0.0/12
    networks:
      - proxy
    labels:
      - arcane.icon=${COMPOSE_PROJECT_NAME}
      - traefik.enable=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=https
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_PROJECT_NAME}.${DOMAIN}`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=${CERT_RESOLVER}
      - traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=3552