name: &stack immich

x-arcane:
  icon: *stack
  urls:
    - ${COMPOSE_PROJECT_NAME}.${DOMAIN}

x-common: &common
  restart: unless-stopped

secrets:
  immich_db_user:
    file: ./secrets/postgres_username.txt
  immich_db_password:
    file: ./secrets/postgres_password.txt

networks:
  default:
    name: immich_network
  proxy:
    external: true

volumes:
  upload:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NAS_IP},rw,nfsvers=4
      device: ":/media/SSD-Storage/Data/Gallery/immich"
  immich_pgdata:
    external: true
  immich_mlmodels:
    external: true
  redis:
  appdata:

services:
  application:
    <<: *common
    container_name: ${COMPOSE_PROJECT_NAME}-server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    depends_on:
      redis:
        condition: service_healthy
      database:
        condition: service_healthy
    networks:
      - default  # For talking to redis/postgres
      - proxy    # For Traefik
    ports:
      - 2283:2283
    labels:
      - traefik.enable=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=https
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_PROJECT_NAME}.${DOMAIN}`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=cloudflare
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=immich-buffering
      - traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=2283
      - traefik.http.middlewares.immich-buffering.buffering.maxRequestBodyBytes=0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - upload:/usr/src/app/upload
      - appdata:/data

  machine-learning:
    <<: *common
    container_name: ${COMPOSE_PROJECT_NAME}-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
        test: python3 healthcheck.py
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - immich_mlmodels:/cache

  redis:
    <<: *common
    container_name: ${COMPOSE_PROJECT_NAME}-redis
    image: docker.io/valkey/valkey:${VALKEY_VERSION}
    healthcheck:
      test: redis-cli ping || exit 1
    labels:
      arcane.icon: redis
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - redis:/data

  database:
    <<: *common
    container_name: ${COMPOSE_PROJECT_NAME}-postgres
    image: ghcr.io/immich-app/postgres:${POSTGRES_VERSION}
    secrets:
      - immich_db_user
      - immich_db_password
    environment:
      DB_DATABASE_NAME: "immich"
      DB_USERNAME_FILE: /run/secrets/immich_db_user
      DB_PASSWORD_FILE: /run/secrets/immich_db_password
      POSTGRES_INITDB_ARGS: '--data-checksums'
    labels:
      arcane.icon: postgresql
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - immich_pgdata:/var/lib/postgresql/data