x-arcane:
  icon: ${SELFHST_ICONS}/jellyfin.webp
services:
  jellyfin:
    container_name: jellyfin
    image: ghcr.io/hotio/jellyfin:latest
    restart: unless-stopped
    logging:
      driver: json-file
    env_file: .env
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TZ}
    ports:
      - 8096:8096
    volumes:
      - /etc/localtime:/etc/localtime:ro #read-only
      - /docker/appdata/jellyfin:/config
      - /data/media:/data/media:ro #read-only
    labels:
      com.getarcaneapp.arcane.icon: ${SELFHST_ICONS}/jellyfin.webp
