x-arcane:
  icon: ${SELFHST_ICONS:-missing-icon-source}/webp/jellyfin.webp
  urls:
    - https://jellyfin.vm1.REDACTED_DOMAIN_1

services:
  jellyfin:
    image: ghcr.io/hotio/jellyfin:latest
    container_name: ${STACK}
    restart: unless-stopped
    logging:
      driver: json-file
    environment:
      PUID: 1000
      PGID: 1000
    ports:
      - 8096:8096
      - 8920:8920
    networks:
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro #read-only
      - /data/media:/data/media:ro #read-only
      - /docker/appdata/${STACK}:/config
      - /data/metadata:/data/metadata
    labels:
      - com.getarcaneapp.arcane.icon=${SELFHST_ICONS:-missing-icon-source}/webp/${STACK}.webp
      - "traefik.enable=true"
      - "traefik.http.routers.${STACK}.entrypoints=https"
      - "traefik.http.routers.${STACK}.rule=Host(`${STACK}.vm1.REDACTED_DOMAIN_1`)"
      - "traefik.http.routers.${STACK}.tls=true"
      - "traefik.http.routers.${STACK}.tls.certresolver=cloudflare"
      - "traefik.http.services.${STACK}.loadbalancer.server.port=8096"

networks:
  proxy:
    external: true