---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Me:
  - Github:
    - icon: github-light
      href: https://github.com/spencerpilon

- Docs:
  - Homepage:
    - icon: homepage
      href: https://gethomepage.dev/configs/bookmarks/
  - Arcane:
    - icon: arcane
      href: https://getarcane.app/
  - Dockhand:
    - icon: dockhand
      href: https://dockhand.pro/manual/

- Resources:
  - Selfh.st Icons:
    - icon: selfh-st
      href: https://selfh.st/icons/

- Helpful Projects:
  - Awesome Docker Compose:
    - icon: si-awesomelists
      href: https://awesome-docker-compose.com/
  - Runtipi:
    - icon: sh-runtipi
      href: https://runtipi.io/
  - AwesomeMediaServer:
    - icon: si-docker
      href: https://github.com/snackk/awesome-media-center
  - example:
    - icon: 
      href: https://example.com 
