---
title: SP Cloudspace
description: My home mini-lab services
headerStyle: boxedWidgets
layout:
    Services:
        header: false
        Admin:
            Machines:
                style: row
                columns: 4
                useEqualHeights: true
                header: false
                # PfSense:
                # Proxmox:
                # Proxmenux:
                # ZimaOS:
            Shells:
                useEqualHeights: true
                style: row
                columns: 2
                header: false
                #######
                # ZimbaBlade Terminal:
                # DockerVM Terminal:
            Consoles:
                header: false
                style: row
                columns: 3
                Tailscale:
                    header: false
                    # Machines:
                    # IDP:
                Reverse Proxy:
                    header: false
                    # NGINX Proxy Manager:
                Docker:
                    header: false
                    # Arcane:
                    # Dockhand:
        Apps:
            Servarr:
                style: row
                columns: 3
                useEqualHeights: true
                header: false
                # qBitTorrent:
                # Prowlarr:
                # Sonarr:
                # Radarr:
            Media:
                style: row
                columns: 3
                useEqualHeights: true
                header: false
                # Immich:
                # Nextcloud:
                # Jellyfin:
            Tools:
                style: row
                columns: 6
                useEqualHeights: true
                header: false
                # OmniTools:
