x-arcane:
  icon: ${SELFHST_WEBP}/dockhand.webp
services:
  dockhand:
    container_name: dockhand
    image: fnsys/dockhand:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - appdata:/app/data
      - /app/data/projects:/app/data/projects
    labels:
      - com.getarcaneapp.arcane.icon=${SELFHST_WEBP}/dockhand.webp
      - "traefik.enable=true"
      - "traefik.http.routers.dockhand.entrypoints=https"  # Changed from websecure
      - "traefik.http.routers.dockhand.rule=Host(`dockhand.vm1.REDACTED_DOMAIN_1`)"
      - "traefik.http.routers.dockhand.tls=true"
      - "traefik.http.routers.dockhand.tls.certresolver=cloudflare"
      - "traefik.http.services.dockhand.loadbalancer.server.port=3000"
volumes:
  appdata:
networks:
  proxy:
    external: true